In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using
# tf.constant().
vector = tf.constant([4, 4])
scalar = tf.constant(4)
matrix = tf.constant([[4, 4],
                     [4, 4]])


In [4]:
#2. Find the shape, rank and size of the tensors you created in 1.
vector.shape, vector.ndim, tf.size(vector), scalar.shape, scalar.ndim, tf.size(scalar),
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [5]:
#3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
random1 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
random2 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
random1, random2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.74045753, 0.7431841 , 0.77372706, ..., 0.40249145, 0.8145081 ,
         0.3628645 ],
        [0.6593418 , 0.07297444, 0.11307395, ..., 0.1317445 , 0.47596335,
         0.26986516],
        [0.27106082, 0.635905  , 0.3502195 , ..., 0.7015686 , 0.78738   ,
         0.4775045 ],
        [0.9140829 , 0.9425521 , 0.72645295, ..., 0.74237466, 0.5986191 ,
         0.38717616],
        [0.57057774, 0.8796911 , 0.1660974 , ..., 0.16709697, 0.8710315 ,
         0.9151342 ]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7303337 , 0.93706596, 0.67609966, ..., 0.957656  , 0.6152028 ,
         0.00831711],
        [0.2779287 , 0.41684222, 0.3870194 , ..., 0.6313423 , 0.2527287 ,
         0.075611  ],
        [0.15508425, 0.5213343 , 0.78569186, ..., 0.9416901 , 0.9626074 ,
         0.8968483 ],
        [0.8134403 , 0.6825979 , 0.529987  , ..., 0.38157916, 0.76727724,
         0.07917607],
        [0.08343

In [6]:
#4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.multiply(random1, random2)

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.5407811 , 0.6964125 , 0.5231166 , ..., 0.38544837, 0.50108767,
        0.00301799],
       [0.18325002, 0.03041883, 0.04376181, ..., 0.08317588, 0.1202896 ,
        0.02040477],
       [0.04203726, 0.3315191 , 0.2751646 , ..., 0.6606602 , 0.7579378 ,
        0.4282491 ],
       [0.74355185, 0.64338404, 0.3850106 , ..., 0.2832747 , 0.4593068 ,
        0.03065509],
       [0.04760408, 0.5601093 , 0.14030455, ..., 0.13065958, 0.7546244 ,
        0.09777535]], dtype=float32)>

In [7]:
#5. Multiply the two tensors you created in 3 using dot product. We transpose because
# in matrix multiplication the number of rows in the first matrix must be the
# same as the number of columns in the second matrix.
tf.tensordot(tf.transpose(random1), random2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.5572243 , 2.0972567 , 1.9351976 , ..., 2.175581  , 2.0787704 ,
        0.4324479 ],
       [1.5017766 , 2.261844  , 2.272961  , ..., 2.4041348 , 2.5731041 ,
        0.7506253 ],
       [1.2556028 , 1.5563799 , 1.3673582 , ..., 1.5492281 , 1.5429904 ,
        0.4043425 ],
       ...,
       [1.0571895 , 1.4109653 , 1.4089266 , ..., 1.5432186 , 1.6706173 ,
        0.7191409 ],
       [1.408869  , 2.3353493 , 2.4065654 , ..., 2.731496  , 2.5932462 ,
        0.8893824 ],
       [0.80536443, 1.5484205 , 1.7031707 , ..., 1.8308551 , 1.8409917 ,
        0.5801023 ]], dtype=float32)>

In [8]:
#6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
random3 = tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1)
random3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.6711669 , 0.6990595 , 0.28676963],
        [0.23140144, 0.3221972 , 0.9206811 ],
        [0.5398401 , 0.9442729 , 0.60796845],
        ...,
        [0.06094658, 0.4031011 , 0.6106063 ],
        [0.03596365, 0.46853197, 0.57854164],
        [0.541167  , 0.29872584, 0.5317091 ]],

       [[0.43189585, 0.17501628, 0.39900517],
        [0.27068174, 0.9490161 , 0.56445634],
        [0.6278502 , 0.3505447 , 0.98065174],
        ...,
        [0.784464  , 0.14938247, 0.24823737],
        [0.309875  , 0.52990806, 0.8978858 ],
        [0.15469706, 0.7535362 , 0.66734886]],

       [[0.7970935 , 0.37593186, 0.01809907],
        [0.7270943 , 0.17570472, 0.31438875],
        [0.34166837, 0.5054741 , 0.92048013],
        ...,
        [0.57891345, 0.39746833, 0.5312568 ],
        [0.10584986, 0.99623334, 0.6503098 ],
        [0.9053947 , 0.86731803, 0.96496165]],

       ...,

       [[0.31158817, 0.3040656 , 0.25290453],
        [0.98

In [9]:
#7. Find the min and max values of the tensor you created in 6.
min = tf.reduce_min(random3)
max = tf.reduce_max(random3)
min, max

"""
When you calculate the minimum and maximum using tf.reduce_min and tf.reduce_max,
you may see values that are slightly smaller than 0 or slightly larger than 1. This
is expected due to the inherent limitations of floating-point precision.

For example, you may see a minimum value like 5.2452087e-06, which represents a
very small value close to 0, but not exactly 0. Similarly, you may see a maximum
value slightly larger than 1.
"""

'\nWhen you calculate the minimum and maximum using tf.reduce_min and tf.reduce_max,\nyou may see values that are slightly smaller than 0 or slightly larger than 1. This\nis expected due to the inherent limitations of floating-point precision.\n\nFor example, you may see a minimum value like 5.2452087e-06, which represents a\nvery small value close to 0, but not exactly 0. Similarly, you may see a maximum\nvalue slightly larger than 1.\n'

In [13]:
#8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it
# to change the shape to [224, 224, 3].
random4 = tf.random.uniform(shape=(1, 224, 224, 3), minval=0, maxval=1)
random4squeezed = tf.squeeze(random4)
random4squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.23679626, 0.09744227, 0.5835508 ],
        [0.65857196, 0.93073773, 0.47021914],
        [0.6129893 , 0.33424294, 0.95854485],
        ...,
        [0.617332  , 0.2757386 , 0.22013915],
        [0.5373286 , 0.12622178, 0.6807122 ],
        [0.06312811, 0.32469523, 0.13987815]],

       [[0.41809738, 0.8457048 , 0.30487096],
        [0.15904522, 0.84954953, 0.95183396],
        [0.8952321 , 0.75997853, 0.23300219],
        ...,
        [0.6711104 , 0.66534805, 0.1536994 ],
        [0.43057466, 0.23924911, 0.8353251 ],
        [0.29742098, 0.46503842, 0.7534512 ]],

       [[0.7202592 , 0.7193501 , 0.43497217],
        [0.4734831 , 0.533869  , 0.6275742 ],
        [0.34659433, 0.58920264, 0.5351788 ],
        ...,
        [0.44185555, 0.5673002 , 0.3674339 ],
        [0.66420054, 0.4413253 , 0.10681653],
        [0.20477808, 0.18672073, 0.6901456 ]],

       ...,

       [[0.401762  , 0.07707751, 0.31636214],
        [0.80

In [26]:
#9. Create a tensor with shape [10] using your own choice of values, then find the
# index which has the maximum value.
random5 = tf.random.uniform(shape=(10,), minval=0, maxval=100)
print(random5)
print(f"The maximum value of F is at position: {tf.argmax(random5).numpy()}")

tf.Tensor(
[48.747288 82.278076 13.460374 32.88555  42.66746  58.09951  90.1069
  9.567237 10.241472 49.107887], shape=(10,), dtype=float32)
The maximum value of F is at position: 6


In [25]:
# 10. One-hot encode the tensor you created in 9. One-hot encoding is typically
# used for categorical data, where each category is represented as a binary vector.
# It doesn't make much sense to apply one-hot encoding to a tensor of continuous
# or numerical values.
tf.one_hot(random5, depth=4) # The error is because the tensor is made of float values.


InvalidArgumentError: ignored